version: '3.7'

services:
  db:
    # This matches our current Heroku database. Can upgrade to 13 when we upgrade on Heroku
    image: postgres:12.6
    container_name: "cti-db"
    environment:
      - POSTGRES_PASSWORD=cti_password
      - POSTGRES_USER=cti
      - POSTGRES_DB=cti
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  web:
    container_name: "cti-web"
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: ./config/.env
    volumes:
      - .:/code
    ports:
      - 8888:8000
    depends_on:
      - db
  # init:
  #   build: .
  #   command: /bin/sh ./init/provision.sh
  #   environment:
  #     - SU_USERNAME=username
  #     - SU_PASSWORD=password
  #     - SU_EMAIL=admin@civictechindex.org
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db

volumes:
  postgres_data:
