# Generated by Django 3.0.5 on 2020-06-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('WebSite', 'WebSite'), ('MeetUp', 'MeetUp'), ('FaceBook', 'FaceBook'), ('Twitter', 'Twitter'), ('GitHub', 'GitHub')], max_length=200)),
                ('url', models.CharField(max_length=1024)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='data.Organization')),
            ],
        ),
    ]
