# Generated by Django 3.1.8 on 2021-04-19 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliases'
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256, blank=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('github_name', models.CharField(blank=True, max_length=1024)),
                ('github_id', models.IntegerField(blank=True, null=True)),
                ('cti_contributor', models.BooleanField(blank=True, default=None, null=True)),
                ('org_tag', models.CharField(blank=True, max_length=128)),
                ('organization_email', models.EmailField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='submitted', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('WebSite', 'WebSite'), ('MeetUp', 'MeetUp'), ('FaceBook', 'FaceBook'), ('Twitter', 'Twitter'), ('GitHub', 'GitHub')], max_length=200)),
                ('url', models.CharField(max_length=1024)),
                ('http_status', models.CharField(blank=True, max_length=8, null=True)),
                ('http_status_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=4096, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='data.organization')),
            ],
            options={
                'unique_together': {('organization', 'link_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('notification_type', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField(blank=True, max_length=4096)),
                ('live', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('ToBeAnswered', 'To be answered'), ('ToBeDeleted', 'To be deleted'), ('Duplicate', 'Duplicate')], default='New', max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs'
            },
        ),
    ]
