# Generated by Django 3.0.7 on 2020-11-15 19:54
import re
from django.db import migrations


def backwards(apps, schema_editor):
    pass


def forwards(apps, schema_editor):
    # Fill in GitHub name using any available link to github.com
    Link = apps.get_model('data', 'Link')

    for link in Link.objects.filter(link_type='GitHub').select_related('organization').all():
        match = re.match(r'https://github.com/(.*)', link.url)
        if match:
            name = match[1].replace('/', '')
            link.organization.github_name = name
            link.organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_add_github_info_to_organization'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
