# Generated by Django 3.0.7 on 2020-12-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_infer_github_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('ToBeAnswered', 'To be answered'), ('ToBeDeleted', 'To be deleted'), ('Duplicate', 'Duplicate')], default='New', max_length=100),
        ),
    ]
