# Generated by Django 3.0.7 on 2021-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='http_status',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='http_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='notes',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
