# Generated by Django 3.0.7 on 2021-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cti_contributor',
            field=models.NullBooleanField(default=None),
        ),
    ]
