# Generated by Django 3.1.7 on 2021-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_organization_org_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
