# Generated by Django 3.1.7 on 2021-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_split_org_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cti_contributor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
