# Generated by Django 3.1.7 on 2021-04-07 05:07
from django.db import migrations


def backwards(apps, schema_editor):
    Organization = apps.get_model('data', 'Organization')
    Organization.objects.update(status='submitted')


def forwards(apps, schema_editor):
    Organization = apps.get_model('data', 'Organization')
    Organization.objects.update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_add_organization_status'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
