# Generated by Django 3.1.5 on 2021-03-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_current_orgs_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('import_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('github_name', models.CharField(blank=True, max_length=1024)),
                ('github_id', models.IntegerField(blank=True, null=True)),
                ('cti_contributor', models.BooleanField(blank=True, default=None, null=True)),
                ('org_tag', models.CharField(blank=True, max_length=128)),
                ('organization_email', models.EmailField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='submitted', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('WebSite', 'WebSite'), ('MeetUp', 'MeetUp'), ('FaceBook', 'FaceBook'), ('Twitter', 'Twitter'), ('GitHub', 'GitHub')], max_length=200)),
                ('url', models.CharField(max_length=1024)),
                ('http_status', models.CharField(blank=True, max_length=8, null=True)),
                ('http_status_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=4096, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='data.organization2')),
            ],
            options={
                'unique_together': {('organization', 'link_type')},
            },
        ),
    ]
